web:
  image: paulohms/jivaw:3.19.12
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - PACOTE_JIVAW=jiva-w_3.20b67.pkg
  command: java -jar /opt/DPM/docker-package-manager.jar
  volumes: data-volume:/opt/
