web:
  image: paulohms/jivaw:3.19.12
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - PACOTE_JIVAW=jiva-w_3.20b67.pkg
  command: ["/bin/sh","-c", "java -jar /opt/DPM/docker-package-manager.jar", "tail -f /opt/jboss_producao/leia_me.txt"]
  volumes: 
    - /home/rancher/data/jboss_producao/:/opt/jboss_producao/
