web:
  image: paulohms/jivaw:3.19.12
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - PACOTE_JIVAW=jiva-w_3.20b67.pkg
  command: ["/bin/sh","-c", "java -jar /opt/DPM/docker-package-manager.jar && /opt/jboss_producao/bin/./jboss_init_redhat.sh start -Djape.lazy.init=true -Djape.lob.fields.as.lazy=true -Djape.ignore.ligacao.inconsistente=true && tail -F /opt/jboss_producao/server/default/log/server.log"]
  volumes: 
    - dados-cliente/${usuario_bd}:/opt/jboss_producao/server