.catalog:
  name: "Jiva-W"
  version: "3.20"
  description: "Criar um novo container utilizando o template"
  questions:
    - variable: "ip_bd"
      label: "IP do Banco de Dados"
      description: |
        IP no qual está instalado o Banco de Dados
      type: "string"
      required: true
    - variable: "porta_bd"
      label: "Porta do Banco de Dados"
      description: |
        Porta no qual está instalado o Banco de Dados
      type: "string"
      default: "1521"
      required: true
    - variable: "sid_bd"
      label: "SID do Banco de Dados"
      description: |
        SID do Banco de Dados
      type: "string"
      default: "ORCL"
      required: true
    - variable: "usuario_bd"
      label: "Usuário do Banco de Dados"
      description: |
        Usuário do Banco de Dados
      type: "string"
      required: true
    - variable: "senha_bd"
      label: "Senha do Banco de Dados"
      description: |
        Senha do Banco de Dados
      type: "string"
      required: true
    - variable: "porta_load_balancer"
      label: "Porta no qual a aplicação será exposta"
      description: |
        Porta no qual a aplicação será exposta
      type: "string"
      required: true
web:
  scale: 1
  health_check:
      port: 8080
      request_line: GET /healthcheck HTTP/1.0
      interval: 6000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 10
      strategy: recreate
      healthy_threshold: 8
      response_timeout: 2000
load-balancer:
    scale: 1
    lb_config:
      port_rules:
      - hostname: ''
        path: ''
        priority: 1
        protocol: http
        service: web
        source_port: ${porta_load_balancer}
        target_port: 8080
